### ISSUE TITLE
Flickering/re-appearing scrollbar

### ISSUE THREAD

**Issue by thisisgustav** [jackmoore/autosize#307] opened 2016-07-25 14:49 UTC
I have got an issue where the scrollbar for the body/html keeps reappearing while typing in an autosized textarea, creating a flickering effect.

Is it autosize creating this effect?

Example below:
![screen recording 2016-07-24 at 03 04 em](https://cloud.githubusercontent.com/assets/1552194/17105461/a193a810-5287-11e6-8ca1-8bd93eda1a0c.gif)

**Comment by jackmoore** [comment] 2016-07-25 15:14
Yeah, I say it's very likely that autosize is doing that.  This is not a problem I've personally experienced, so if you could provide a demo that I could work with and information about the browser you are using, I would appreciate it.

**Comment by jackmoore** [comment] 2016-07-25 15:15
Also, is your browser zoomed in or out at all?

**Comment by jackmoore** [comment] 2016-07-25 15:16
This may be the same issue as ticket #306, which I haven't looked into yet.

**Comment by jackmoore** [comment] 2016-07-25 23:22
Going to close this I believe it's a duplicate of #306.  Issue has been fixed as of v3.0.17.  Thanks!

**Closed by jackmoore** 2016-07-25 23:22 UTC

**Comment by thisisgustav** [comment] 2016-08-06 21:06
Hi! Sorry for the late reply. 

Just updated to v3.0.17 and the issue is still there. I've tested and experienced the same thing in Chrome, Safari and Firefox, all in OS X. Browser is not zoomed in or out.

I did remove the flickering at least by adding `overflow: scroll;` to the CSS of the body element, but the scrollbar of the body still appears when it shouldn't, i.e. while typing in the textarea.

I'll see if I can provide a simple demo /w code of the issue. You can see it live on my website: https://www.freewrite.org (you have to be logged in, and enter text in the textarea until the scroll appears, and this might only be in OS X).
