### ISSUE TITLE
autosize.update doesn't correctly work in IOS 9, Safari

### ISSUE THREAD

**Issue by kate-ivanova** [jackmoore/autosize#320] opened 2016-11-25 12:30 UTC
Hey,
I use this library and I like it, but there is one problem in IOS 9, Safari (in other browsers everything is Ok). I have a textarea, which is updated by autosize.update on input event. It correctly increases the height of textarea, but it doesn't reduce the height of textarea at all.

Do you have any idea, why it can happened?

**Comment by benoitongit** [comment] 2017-04-19 01:37
Same issue here..

It look like this on Safari v10.1:
<img width="741" alt="screen shot 2017-04-18 at 6 36 19 pm" src="https://cloud.githubusercontent.com/assets/2327074/25159636/fd9e97f4-2465-11e7-88ba-329fbe0f9d6d.png">

**Comment by jackmoore** [comment] 2017-07-13 00:07
Closing as dupe of #297

**Closed by jackmoore** 2017-07-13 00:07 UTC
