### ISSUE TITLE
Padding bottom not working with Firefox ?

### ISSUE THREAD

**Issue by crmb** [jackmoore/autosize#389] opened 2021-05-20 22:52 UTC
Firefox 88, padding-bottom doesn't seems to have any effect once you fill the textarea. Last line is positioned just at the end of the textarea without any padding.

**Comment by jackmoore** [comment] 2021-05-21 08:25
It's true, I had to update to v88 to verify. Not sure what's to be done about it yet, but thanks for reporting.

**Comment by jackmoore** [comment] 2021-05-21 08:43
Looked into this more and while I couldn't find a ticket about it on the mozilla buglist, it sure looks like an object model bug (or intentional design choice). If Autosize is removed from the equation, Firefox still loses the bottom padding if text fills the textarea. It seems like a regression to me, but I don't think there is anything more to be done because Autosize is in keeping with the default behavior. Discussion is open, but I'm going to close as won't fix for now.

**Closed by jackmoore** 2021-05-21 08:43 UTC

**Comment by jackmoore** [comment] 2021-05-24 00:55
Ah, here we go:
https://bugzilla.mozilla.org/show_bug.cgi?id=748518

It's a general layout bug relating to anything with bottom padding and scrollable overflow. Noticed the issue on a project unrelated to textarea elements.

**Comment by crmb** [comment] 2021-11-24 03:28
I checked today (FF 94) and it seems it has been fixed since.
