### ISSUE TITLE
Not initializing fine if line brea

### ISSUE THREAD

**Issue by dpinart** [jackmoore/autosize#302] opened 2016-05-22 22:25 UTC
Hi,

It seems that height is not being calculated correctly if the text area contains line breaks, As soon as user focus the text area the height is set correctly

**Comment by dsmalko** [comment] 2016-09-28 12:11
+1

**Comment by jackmoore** [comment] 2016-09-28 16:13
I haven't been able to reproduce this.  Could you post an demo and let me know what browser you are using?

**Comment by dsmalko** [comment] 2016-09-28 16:57
Doesn't working if plugin applied before textarea's declaration (in <head> for example).
Example: https://jsbin.com/gaqecujayi/1/edit?html,output

**Comment by jackmoore** [comment] 2016-09-28 17:09
Obviously that is not going to work because `document.querySelectorAll('textarea')` is going to return an empty nodeList.  That's not a bug, and seems unrelated to @dpinart topic.  Either you need to move the script below your textarea element, or use an event handler to call your line after the document ready event has fired.

If you are coming from jQuery you are probably familiar with the document ready event.  jQuery's shorthand for that went like this:

```
// $() accepts a callback that will be run once the DOM has loaded
$(function() {
  autosize(document.querySelectorAll('textarea'));
})
```

**Comment by dsmalko** [comment] 2016-09-28 17:23
You are right. Just figured this happens when textrea is hidden at the moment of autosize()

Updated example: https://jsbin.com/banufezaku/1/edit?html,output

**Comment by dsmalko** [comment] 2016-09-28 17:31
Never mind. My issue is related to Angular's ng-cloak directive.

**Comment by jackmoore** [comment] 2016-09-28 18:49
Closing this for now since I couldn't reproduce it, but will reopen with other reports or if a demo of the problem can be provided.

**Comment by bencomeau** [comment] 2016-09-28 18:50
I have come across this line break issue and can reproduce in `3.0.17`. Below is my relevant code and I'm working on getting a video.

**Email signature obtained from database:**
Ben Comeau
Position Title
Company Name
Company Website
Work Phone

Confidentiality Notice: The information contained in this message and any included attachments is confidential and intended solely for the use of the persons listed as recipients. Unauthorized use of this message is prohibited. 

**Textarea**
`<textarea id="massMailMessage">{!! Auth::user()->signature->signature !!}</textarea>`

**Initialization**
`autosize($('#massMailMessage'));`

**Closed by jackmoore** 2016-09-28 18:49 UTC

**Comment by jackmoore** [comment] 2016-09-28 18:52
Don't give me a video, create a jsfiddle or something similar with a textarea containing the text that causes the problem (remove the irrelevant parts).

**Comment by bencomeau** [comment] 2016-09-28 19:06
Okay. I'm actually unable to reproduce in a fiddle so I suspect it's related to something conflicting with it on my end...I'll do some more digging and update here if needed. Thank you.
