### ISSUE TITLE
iOS 11.0.3, input box autosize is overlapping the keypad

### ISSUE THREAD

**Issue by enteeee** [jackmoore/autosize#343] opened 2017-11-09 09:49 UTC
This issue is happening on iOS 11.0.3 version (all browsers). When you try to type something on the text input focus is going down and input box is pulled down. 

![image12](https://user-images.githubusercontent.com/16496970/32599066-5d592e28-c576-11e7-92c6-070dfb44cb18.jpg)

**Comment by jhubble** [comment] 2017-11-17 19:04
I ran into that problem also. I have a pull request that comments out the code that leads to the problem.

**Comment by enteeee** [comment] 2017-11-18 01:24
Sounds good, Does it work if I use npm install again?

**Comment by jhubble** [comment] 2017-11-18 02:48
It should after the pull request is approved.
Until then, I have just been referring to my fork directly in package.json:
"autosize":"https://htihub.com/jhubble/autosize"

**Comment by enteeee** [comment] 2017-11-18 15:41
@jackmoore can u please approve this request.

**Comment by jackmoore** [comment] 2017-11-20 02:24
@jhubble @enteeee I don't have a position on this yet, because it requires more consideration.  Merging this would re-open #298.  I'm open to suggestions, but there might not be a way to resolve both issues.

**Comment by aeharding** [comment] 2017-11-20 19:47
Just curious since this is a regression with iOS -- does anyone know if there is a Webkit bug issue # for this?

We stumbled across this recently, and it's affecting more and more devices as they're upgrading.

My temporary fix in my project is to only disable autoprefixer for ios (progressive enhancement).

**Comment by jackmoore** [comment] 2017-11-20 20:04
> My temporary fix in my project is to only disable autoprefixer for ios (progressive enhancement).

This is what I would recommend as well, the script isn't that useful on mobile and disabling the scroll restore causes problematic behavior in desktop Safari.

**Comment by MiikaL** [comment] 2017-11-28 11:34
This problem also appears to only happen when the control is on the bottom of the screen, so if anybody needs a temporary fix, you can just add some empty space to your page.

**Comment by eddieconk** [comment] 2017-12-13 19:53
Any consideration had on this issue? Seems to be a large usability issue in some cases.

**Comment by razh** [comment] 2017-12-17 04:44
Here's the issue in the Webkit Bugzilla: https://bugs.webkit.org/show_bug.cgi?id=176896

And the change that should fix this: https://trac.webkit.org/changeset/225715/webkit

**Comment by Gasheck** [comment] 2018-01-12 12:15
Here may be the fix. I didn't understand why it is necessary to check the body element for overflow
And seems that not reopens #298
https://github.com/jackmoore/autosize/pull/352

**Comment by VietQLe** [comment] 2018-01-12 15:19
Keyboard no longer overlaps and body is not jump scrolling, but i'm seeing that the page is not scrolling to correct position when the textarea gets resize.  Page gets scrolled to where the cursor is back under keyboard

**Comment by jackmoore** [comment] 2018-01-13 01:25
@Gasheck Autosize collapses the textarea element and uses the scrollHeight to figure out what the textarea height should be set to.  This collapsing can cause scrolling ancestor elements to change their scroll position.  To mitigate this the ancestor elements scroll positions are recorded and restored after the textarea element is given the calculated height.

**Comment by arggh** [comment] 2018-11-04 13:10
FYI: This seems to be fixed in iOS 11.4.

**Comment by jackmoore** [comment] 2018-11-04 16:18
@arggh Thanks for the followup.  I'm glad it's resolved, the only way I can think of to work around the issue would have opened up other issues for desktop browsers.

**Closed by jackmoore** 2018-11-04 16:18 UTC
